
#include <linux/ioctl.h>


#define DEVICE4MB_IOC_MAGIC 'k'

#define DEVICE4MB_IOCHELLO	_IO(DEVICE4MB_IOC_MAGIC, 1)
#define DEVICE4MB_IOCGET	_IOR(DEVICE4MB_IOC_MAGIC, 2, int)
#define DEVICE4MB_IOCSET	_IOW(DEVICE4MB_IOC_MAGIC, 3, int)
#define DEVICE4MB_IOCGETSET	_IOWR(DEVICE4MB_IOC_MAGIC, 4, int)

#define DEVICE4MB_IOC_MAXNR 4
